on: [push]
name: Deploy

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_URI: ${{ secrets.DATABASE_URI }}
          envkey_DATABASE_SSL: "true"
          envkey_STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
          envkey_STORAGE_ACCOUNT_KEY: ${{ secrets.STORAGE_ACCOUNT_KEY }}
          envkey_STORAGE_URL: ${{ secrets.STORAGE_URL }}
          envkey_STORAGE_CONTAINER_NAME: ${{ secrets.STORAGE_CONTAINER_NAME }}
          envkey_STORAGE_CDN_URL: ${{ secrets.STORAGE_CDN_URL }}
          file_name: .env

      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/kjvstrapi:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/kjvstrapi:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'kjv-strapi'
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/kjvstrapi:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout
